{{- define "lib.atlasSchema" -}}
{{- $appName := regexReplaceAll "-(prod|staging|dev)$" .Release.Name "" -}}
{{- range .Values.atlasSchema -}}
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: {{ $appName }}-{{ .name }}
  labels:
    runs-on: {{ .runsOn }}
    instance: {{ $appName }}-{{ .name }}
    component: {{ .component | default "schema"}}
    part-of: {{ $appName }}
spec:
  urlFrom:
    secretKeyRef:
      key: {{ .secretKey | default "url" }}
      name: {{ .secretName }}
  schema:
    configMapKeyRef:
      key: {{ .schemaCMKey }}
      name: {{ .schemaCMName }}
---
{{- end -}}
{{- end -}}
