{{- define "lib.configMap" -}}
{{- $appName := regexReplaceAll "-(prod|staging|dev)$" .Release.Name "" -}}
{{- range .Values.configMap -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $appName }}-{{ .name }}
  labels:
    runs-on: {{ .runsOn }}
    instance: {{ $appName }}-{{ .name }}
    component: {{ .component | default "config"}}
    part-of: {{ $appName }}
  annotations:
    "helm.sh/hook": {{ .helmHook | default "pre-install" | quote }}
    "helm.sh/hook-weight": {{ .helmWeight | default "-5" | quote }}
data:
{{- range $key, $val := .schemas }}
  {{ $key }}: |
{{ $val | indent 4 }}
{{- end }}
{{- range $key, $val := .settings }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
---
{{- end -}}
{{- end -}}
