{{- define "lib.database" -}}
{{- $appName := regexReplaceAll "-(prod|staging|dev)$" .Release.Name "" -}}
{{- range .Values.database -}}
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ $appName }}-{{ .name }} 
  labels:
    runs-on: {{ .cluster | default "database-cluster" }}
    instance: {{ $appName }}-{{ .name }}
    component: {{ .component | default "database"}}
    part-of: {{ $appName }}
  annotations:
    "helm.sh/hook": {{ .helmHook | default "pre-install" | quote }}
    "helm.sh/hook-weight": {{ .helmWeight | default "-5" | quote }}
spec:
  name: {{ $appName }}
  owner: {{ $appName }}
  cluster:
    name: {{ .cluster | default "database-cluster" }}
  databaseReclaimPolicy: {{ .databaseReclaimPolicy | default "retain" }}
---
{{- end -}}
{{- end -}}
