{{- define "lib.deployment" -}}
{{- $appName := regexReplaceAll "-(prod|staging|dev)$" .Release.Name "" -}}
{{- range .Values.deployment -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-{{ .name }}
  labels:
    runs-on: {{ .runsOn }}
    instance: {{ $appName }}-{{ .name }}
    component: {{ .component }}
    part-of: {{ $appName }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      instance: {{ $appName }}-{{ .name }}
  template:
    metadata:
      labels:
        runs-on: {{ .runsOn }}
        instance: {{ $appName }}-{{ .name }}
        component: {{ .component }}
        part-of: {{ $appName }}
    spec:
      {{- if .imagePullSecret }}
      imagePullSecrets:
        - name: {{ .imagePullSecret }}
      {{- end }}
      {{- if .serviceAccountName }}
      serviceAccountName: {{ .serviceAccountName }}
      {{- end }}
      containers:
        - name: {{ $appName }}-{{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy | default "IfNotPresent" }} 
          ports:
            - containerPort: {{ .containerPort }}
          {{- if .envSecretRefs }}
          envFrom:
            {{- range .envSecretRefs }}
            - secretRef:
                name: {{ $appName }}-{{ . }}
            {{- end }}
          {{- end }}
          {{- if .envVars }}
          env:
          {{- range .envVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          {{- if .probes }}
          {{- toYaml .probes | nindent 10 }}
          {{- end }}
---
{{- end -}}
{{- end -}}
