{{- define "lib.route" -}}
{{- $appName := regexReplaceAll "-(prod|staging|dev)$" .Release.Name "" -}}
{{- range .Values.routes -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $appName }}-{{ .name }}
  labels:
    runs-on: {{ .runsOn }}
    instance: {{ $appName }}-{{ .name }}
    component: {{ .component | default "httpRoute" }}
    part-of: {{ $appName }}
spec:
  parentRefs:
    - name: {{ $.Values.env }}-gateway
      kind: Gateway
  hostnames:
    - {{ .host }}
  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /
       backendRefs:
        - name: {{ $appName }}-{{ .runsOn }}
          port: {{ .port | default 80 }}
---
{{- end -}}
{{- end -}}