{{- define "lib.secret" -}}
{{- $appName := regexReplaceAll "-(prod|staging|dev)$" .Release.Name "" -}}
{{- range .Values.secrets -}}
{{- $runsOnList := required "A valid runsOnList is required!" .runsOnList -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $appName }}-{{ .name }}
  labels:
    {{- if .runsOn }}
    runs-on: {{ .runsOn }}
    {{- end }}
    {{- range .runsOnList }}
    runs-on-{{ . }}: "true"
    {{- end }}
    instance: {{ $appName }}-{{ .name }}
    component: {{ .component | default "sealedSecret" }}
    part-of: {{ $appName }}
spec:
  encryptedData:
{{ toYaml .data | indent 4 }}
  template:
    metadata:
      name: {{ $appName }}-{{ .name }}
      labels:
        {{- if .runsOn }}
        runs-on: {{ .runsOn }}
        {{- end }}
        {{- range .runsOnList }}
        runs-on-{{ . }}: "true"
        {{- end }}
        instance: {{ $appName }}-{{ .name }}
        component: {{ .component | default "secret" }}
        part-of: {{ $appName }}
---
{{- end -}}
{{- end -}}