{{- define "lib.service" -}}
{{- $appName := regexReplaceAll "-(prod|staging|dev)$" .Release.Name "" -}}
{{- range .Values.services -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-{{ .name }}
  labels:
    runs-on: {{ .runsOn }}
    instance: {{ $appName }}-{{ .name }}
    component: {{ .component | default "service" }}
    part-of: {{ $appName }}
spec:
  selector:
    instance: {{ $appName }}-{{ .runsOn }}
  ports:
    - port: {{ .port | default 80 }}
      targetPort: {{ .targetPort }}
---
{{- end -}}
{{- end -}}