{{- define "lib.statefulsets" -}}
{{- $appName := regexReplaceAll "-(prod|staging|dev)$" .Release.Name "" -}}
{{- range .Values.statefulsets -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $appName }}-{{ .name }}
  labels:
    runs-on: {{ .runsOn }}
    instance: {{ $appName }}-{{ .name }}
    component: {{ .component | default "db"}}
    part-of: {{ $appName }}
spec:
  serviceName: {{ $appName }}-{{ .name }}-service
  replicas: 1
  selector:
    matchLabels:
      instance: {{ $appName }}-{{ .name }}
  template:
    metadata:
      labels:
        runs-on: {{ .runsOn }}
        instance: {{ $appName }}-{{ .name }}
        component: {{ .component | default "database"}}
        part-of: {{ $appName }}
    spec:
      {{- if .imagePullSecret }}
      imagePullSecrets:
        - name: {{ .imagePullSecret }}
      {{- end }}
      containers:
        - name: {{ $appName }}-{{ .name }}
          image: {{ .image}}
          imagePullPolicy: IfNotPresent 
          {{- if .envSecretRefs }}
          envFrom:
            {{- range .envSecretRefs }}
            - secretRef:
                name: {{ $appName }}-{{ . }}
            {{- end }}
          {{- end }}
          {{- if .envVars }}
          env:
          {{- range .envVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .containerPort }}
          volumeMounts:
            - mountPath: {{ .mountPath }}
              name: {{ $appName }}-{{ .name }}
  volumeClaimTemplates:
    - metadata:
        name: {{ $appName }}-{{ .name }}
        labels:
          runs-on: {{ .name }}
          instance: {{ $appName }}-{{ .name }}
          component: {{ .component | default "privateVolumeClaim"}}
          part-of: {{ $appName }}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .storage }}
---
{{- end -}}
{{- end -}}
